# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: python-compileall
        name: python-compileall
        entry: python3 -m compileall app/
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit, push]
